language: c
matrix:
  include:
    - complier: clang
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: GCC_VERSION=5

script:
  - mkdir cmake && cd cmake && cmake .. && make
