language: c
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: CC=/usr/bin/gcc-5
    - complier: clang

script:
  - mkdir cmake && cd cmake && cmake .. && make
