language: c
matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - rpm
    env: COMPILER=gcc-5
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - rpm
    env: COMPILER=clang-3.7
script:
- mkdir cmake
- cd cmake
- cmake -DCMAKE_C_COMPILER=$COMPILER .. && make package
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "${GITHUB_KEY}"
  file_glob: true
  file:
    - "build/packages/roflcopter-*.rpm"
    - "build/packages/roflcopter-*.deb"
  on:
    tags: true
