.\" roflcopter.1
.\"
.\" Lets watch a sweet roflcopter fly.
.\"
.\" Author:  Justin Helgesen
.\"          justinhelgesen@gmail.com
.\" Created: 9/4/2016
.\"
.\" The MIT License (MIT)
.\" Copyright (c) 2016 Justin Helgesen
.TH ROFLCOPTER 1 "September 5th, 2016" Linux "User Manuals"
.SH NAME
roflcopter \- Watch a pretty roflcopter air show
.SH SYNOPSIS
.B roflcopter [OPTION]
.SH DESCRIPTION
.B roflcopter
is a highly advanced animation of a roflcopter flying across your screen
.PP
.TP
.B \-h, --help
Print the help message
.TP
.B \-e, --evil
Run Evil Mode
.SH EXAMPLE
.TP
.B roflcopter
Watch the standard show
.TP
.B roflcopter -e
Watch the Evil Mode show
.TP
.B roflcopter -h
Print the boring old help message
.SH BUGS
The roflcopter some times doesn't know when to quit
.SH AUTHOR
Justin Helgesen (justinhelgesen@gmail.com)
.SH COPYRIGHT
The MIT License (MIT)
.PP
Copyright (c) 2016 Justin Helgesen
.SH SEE ALSO
.BR sl (1)
