.\" roflcopter.1
.\"
.\" Lets watch a sweet roflcopter fly.
.\"
.\" Author:  Justin Helgesen
.\"          justinhelgesen@gmail.com
.\" Created: 9/4/2016
.\"
.\" The MIT License (MIT)
.\" Copyright (c) 2016 Justin Helgesen
.TH ROFLCOPTER 1 "September 5th, 2016" Linux "User Manuals"
.SH NAME
roflcopter \- Watch a pretty roflcopter air show
.SH SYNOPSIS
.B roflcopter
.SH DESCRIPTION
.B roflcopter
is a highly advanced animation of a roflcopter flying across your screen.
.SH BUGS
roflcopter doesn't crash :(
.SH AUTHOR
Justin Helgesen (justinhelgesen@gmail.com)
.SH COPYRIGHT
The MIT License (MIT)

Copyright (c) 2016 Justin Helgesen
.SH SEE ALSO
.BR sl (1)
